name: SHRP CI
on:
  workflow_dispatch:
    inputs:
      pushtosf:
        description: 'set this to true if you wanna push to sf (all small)'
        required: true
env:
  MANIFEST: "git://github.com/SHRP/manifest.git -b v3_11.0"
  # Recovery Manifest URL with -b branch
  DT_LINK: "https://github.com/AmyTheBuildBot/device_xiaomi_wayne"
  # Your Device Tree Link
  VENDOR: "xiaomi"
  # Your Device's Vendor name as in used inside DT. Example: xiaomi, samsung, asus, etc.
  CODENAME: "wayne"
  # Your Device's Codename as in used inside DT." Example: nikel, phoenix, ginkgo, etc.
  KERNEL_LINK: ""
  # Kernel repo link with optional -b branch. Only for building kernel from source. Ignore if using prebuilt.
  TARGET: "bootimage"
  # Set as recoveryimage (or bootimage if no recovery partition avaiable)
  FLAVOR: "eng"
  # eng by default, change the variable if you want userdebug
  EXTRA_CMD: "git clone https://github.com/omnirom/android_vendor_qcom_opensource_commonsys --depth=1 -b android-9.0 vendor/qcom/opensource/commonsys"
  # For qualcomm FDE devices put git clone https://github.com/omnirom/android_vendor_qcom_opensource_commonsys --depth=1 -b android-9.0 vendor/qcom/opensource/commonsys in EXTRA CMD
  # If you want to Execute any external Command Before Compilation Starts
  TZ: "Europe/Berlin"

jobs:
  shrpCI:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main
       - name: Recovery Compilation
         uses: ElytrA8/Recovery-Compiler@production
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@master

